pub mod audio;
pub mod audio_cache;
pub mod bot;
pub mod config;
pub mod error;
#[cfg(windows)]
pub mod gui_native;
pub mod hints;
pub mod i18n;
pub mod logging;
pub mod net;
pub mod paths;
pub mod postupdate;
pub mod player;
pub mod proc;
#[cfg(target_os = "linux")]
pub mod control;
#[cfg(target_os = "linux")]
pub mod doctor;
#[cfg(target_os = "linux")]
pub mod editor;
#[cfg(target_os = "linux")]
pub mod install;
#[cfg(target_os = "linux")]
pub mod runlock;
#[cfg(target_os = "linux")]
pub mod service;
pub mod services;
pub mod spotify;
pub mod settings;
pub mod track;
pub mod update;
pub mod tt;
pub mod wizard;
pub mod youtube;

